/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilesIndexRouteImport } from './routes/profiles.index'
import { Route as ProfilesProfileIdRouteImport } from './routes/profiles.$profileId'

const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfilesRoute,
} as any)
const ProfilesProfileIdRoute = ProfilesProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => ProfilesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/profiles': typeof ProfilesRouteWithChildren
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/profiles/': typeof ProfilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/profiles': typeof ProfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/profiles': typeof ProfilesRouteWithChildren
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/profiles/': typeof ProfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/profiles'
    | '/profiles/$profileId'
    | '/profiles/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products' | '/profiles/$profileId' | '/profiles'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/profiles'
    | '/profiles/$profileId'
    | '/profiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRoute: typeof ProductsRoute
  ProfilesRoute: typeof ProfilesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof ProfilesRoute
    }
    '/profiles/$profileId': {
      id: '/profiles/$profileId'
      path: '/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof ProfilesProfileIdRouteImport
      parentRoute: typeof ProfilesRoute
    }
  }
}

interface ProfilesRouteChildren {
  ProfilesProfileIdRoute: typeof ProfilesProfileIdRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
}

const ProfilesRouteChildren: ProfilesRouteChildren = {
  ProfilesProfileIdRoute: ProfilesProfileIdRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
}

const ProfilesRouteWithChildren = ProfilesRoute._addFileChildren(
  ProfilesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRoute: ProductsRoute,
  ProfilesRoute: ProfilesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
